language: c
jobs:
  include:
    - name: aarch64 / arm minimal tests / ocaml tests
      os: linux
      arch: arm64
      dist: bionic
      install:
        - sudo add-apt-repository -y ppa:avsm/ppa
        - sudo apt update -qq --yes && sudo apt install -qq --yes opam aspcud ocaml
        - opam init --yes --bare
        - opam switch create 4.09.1 --yes
        - eval $(opam config env)
        - opam install --yes cppo ctypes ctypes-foreign dune zarith
    - name: gcc 7 / full tests
      os: linux
      compiler: gcc
      dist: bionic
    - name: gcc 5.4 / full tests / ocaml 4.09.1 / ocaml tests
      install:
        - sudo add-apt-repository -y ppa:avsm/ppa
        - sudo apt update -qq --yes && sudo apt install -qq --yes opam aspcud ocaml
        - opam init --yes --bare
        - opam switch create 4.09.1 --yes
        - eval $(opam config env)
        - opam install --yes cppo ctypes ctypes-foreign dune zarith
    - name: clang 7 / full tests
      os: linux
      compiler: clang
    - name: xcode 10 / full tests
      os: osx
      osx_image: xcode10.1
    - name: xcode 11 / full tests
      os: osx
      osx_image: xcode11.3
    - name: test/win
      os: windows
      compiler: msvc
      env:
        - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/14.0/Bin"
      install:
        - export PATH="$MSBUILD_PATH:$PATH"
        - choco install -y visualstudio2017community visualstudio2017-workload-nativecrossplat
        - choco install visualstudio2017-workload-vctools -y
script:
  - .ci/script.sh
