language: c
jobs:
  include:
    - name: aarch64 / arm minimal tests / ocaml tests
      os: linux
      arch: arm64
      dist: bionic
      install:
        - sudo add-apt-repository -y ppa:avsm/ppa
        - sudo apt update -qq --yes && sudo apt install -qq --yes opam aspcud ocaml
        - opam init --yes --bare
        - opam switch create 4.09.1 --yes
        - eval $(opam config env)
        - opam install --yes cppo ctypes ctypes-foreign dune zarith
    - name: gcc 7 / full tests
      os: linux
      compiler: gcc
      dist: bionic
    - name: gcc 5.4 / full tests / ocaml 4.09.1 / ocaml tests
      install:
        - sudo add-apt-repository -y ppa:avsm/ppa
        - sudo apt update -qq --yes && sudo apt install -qq --yes opam aspcud ocaml
        - opam init --yes --bare
        - opam switch create 4.09.1 --yes
        - eval $(opam config env)
        - opam install --yes cppo ctypes ctypes-foreign dune zarith
    - name: clang 7 / full tests
      os: linux
      compiler: clang
    - name: 32-bit / compile-only
      os: linux
      install:
        - export TARGET=IA32
    - name: xcode 10 / full tests
      os: osx
      osx_image: xcode10.1
    - name: xcode 11 / full tests
      os: osx
      osx_image: xcode11.3
    - name: vs2017 / compile-only
      os: windows
    - name: ARM cross / aarch64-none-linux-gnu / build only
      os: linux
      before_script:
        - curl -L -O https://developer.arm.com/-/media/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.xz
        - tar -xf gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.xz
      env: ARM_CROSS_CI=aarch64-none-linux-gnu
script:
  - .ci/script.sh
